<a href="https://colab.research.google.com/github/farhankhan19032003-lgtm/expoloratory-data-analysis/blob/main/pandasoneshot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
dict1 = {
    "name" : ['farhan','gufran','imran'],
    "marks" : [90,95,88],
    "place" : ['lahore', 'karachi','islamabad']
}

In [ ]:
df = pd.DataFrame(dict1)

In [ ]:
df

     name  marks      place
0  farhan     90     lahore
1  gufran     95    karachi
2   imran     88  islamabad

In [ ]:
df.describe()

           marks
count   3.000000
mean   91.000000
std     3.605551
min    88.000000
25%    89.000000
50%    90.000000
75%    92.500000
max    95.000000

In [ ]:
df.tail()

     name  marks      place
0  farhan     90     lahore
1  gufran     95    karachi
2   imran     88  islamabad

In [ ]:
df.to_csv('farhan.csv')

In [ ]:
df.to_csv('farhan.csv', index = False)

In [ ]:
ser = pd.Series(np.random.rand(34))

In [ ]:
type(ser)

pandas.core.series.Series

In [ ]:
newdf = pd.DataFrame(np.random.rand(10000,10), index = np.arange(10000))

In [ ]:
newdf

,0,1,2,3,4,5,6,7,8,9
0,0.604797,0.494204,0.364167,0.960544,0.043891,0.628084,0.985100,0.279562,0.669178,0.745397
1,0.109137,0.392457,0.114704,0.586682,0.184560,0.402558,0.910222,0.328826,0.520539,0.484018
2,0.341927,0.653088,0.280246,0.963718,0.847224,0.260758,0.652911,0.220852,0.547996,0.096540
3,0.665162,0.598727,0.010558,0.880758,0.748441,0.759492,0.932602,0.807222,0.116099,0.860140
4,0.566893,0.852146,0.959399,0.978795,0.742416,0.580560,0.718030,0.014365,0.502321,0.212576
...,...,...,...,...,...,...,...,...,...,...
9995,0.709617,0.908952,0.440789,0.502836,0.703161,0.801423,0.830903,0.978875,0.991494,0.676988
9996,0.560311,0.610462,0.148220,0.105629,0.008582,0.241477,0.352974,0.430081,0.748771,0.942898
9997,0.928524,0.231218,0.819739,0.364327,0.105919,0.960259,0.324928,0.753413,0.426198,0.635822
9998,0.535498,0.131646,0.747088,0.702190,0.568904,0.673789,0.395890,0.473277,0.171036,0.147524
9999,0.034417,0.310409,0.102685,0.645129,0.678335,0.249791,0.114839,0.231001,0.615867,0.380887

In [ ]:
newdf.describe()

,0,1,2,3,4,5,6,7,8,9
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,0.506601,0.502476,0.505267,0.500900,0.498006,0.499370,0.499099,0.500070,0.496431,0.499186
std,0.289592,0.290320,0.290170,0.289503,0.287850,0.287992,0.287941,0.289442,0.288240,0.289181
min,0.000104,0.000060,0.000032,0.000139,0.000049,0.000291,0.000109,0.000077,0.000020,0.000054
25%,0.253773,0.252776,0.252257,0.252580,0.248042,0.252119,0.251094,0.251846,0.243926,0.246088
50%,0.512170,0.502257,0.510970,0.500547,0.497192,0.494932,0.496462,0.493563,0.494876,0.501700
75%,0.757208,0.753354,0.758513,0.754080,0.747181,0.748973,0.742415,0.752139,0.746631,0.751180
max,0.999944,0.999884,0.999923,0.999824,0.999989,0.999991,0.999888,0.999997,0.999971,0.999780

In [ ]:
newdf[0][0] = "1000000000"

/tmp/ipython-input-1023751446.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "1000000000"
/tmp/ipython-input-1023751446.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1000000000' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "1000000000"

In [ ]:
newdf.head()

,0,1,2,3,4,5,6,7,8,9
0,1000000000,0.494204,0.364167,0.960544,0.043891,0.628084,0.985100,0.279562,0.669178,0.745397
1,0.109137,0.392457,0.114704,0.586682,0.184560,0.402558,0.910222,0.328826,0.520539,0.484018
2,0.341927,0.653088,0.280246,0.963718,0.847224,0.260758,0.652911,0.220852,0.547996,0.096540
3,0.665162,0.598727,0.010558,0.880758,0.748441,0.759492,0.932602,0.807222,0.116099,0.860140
4,0.566893,0.852146,0.959399,0.978795,0.742416,0.580560,0.718030,0.014365,0.502321,0.212576

In [ ]:
newdf.index

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       9990, 9991, 9992, 9993, 9994, 9995, 9996, 9997, 9998, 9999],
      dtype='int64', length=10000)

In [ ]:
newdf.columns

RangeIndex(start=0, stop=10, step=1)

In [ ]:
newdf.to_numpy()

array([['1000000000', 0.49420413854031, 0.3641667946266085, ...,
        0.2795616022577997, 0.6691784223138387, 0.7453968396066841],
       [0.10913745579135303, 0.3924566343659025, 0.11470395395582345,
        ..., 0.32882572773959096, 0.5205394129391678,
        0.48401808592368145],
       [0.3419267220795221, 0.6530884477234172, 0.28024644490153316, ...,
        0.22085226752382592, 0.547996031142613, 0.09653968088539855],
       ...,
       [0.9285244983408117, 0.23121833534747338, 0.8197391494480509, ...,
        0.7534126701735648, 0.4261975650261044, 0.6358224750628398],
       [0.5354983654734481, 0.1316461099460683, 0.7470878493483691, ...,
        0.47327689279159435, 0.17103643292867532, 0.14752403086622345],
       [0.034417210299842016, 0.3104094329891731, 0.1026845430013128,
        ..., 0.23100127320774066, 0.6158666780173446,
        0.38088712213424347]], dtype=object)

In [ ]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
5    float64
6    float64
7    float64
8    float64
9    float64
dtype: object

In [ ]:
newdf[2][2] = "Farhan khan"

/tmp/ipython-input-3424485181.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[2][2] = "Farhan khan"
/tmp/ipython-input-3424485181.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf[2][2] = "Farhan khan"
/tmp/ipython-input-3424485181.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Farhan khan' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[2][2] = "Farhan khan"

In [ ]:
type(newdf)

pandas.core.frame.DataFrame

In [ ]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
0,1000000000,0.109137,0.341927,0.665162,0.566893,0.014012,0.820483,0.865744,0.466946,0.389425,...,0.115956,0.452005,0.630919,0.135745,0.499547,0.709617,0.560311,0.928524,0.535498,0.034417
1,0.494204,0.392457,0.653088,0.598727,0.852146,0.429913,0.944443,0.145462,0.524548,0.384371,...,0.083691,0.585618,0.104548,0.632954,0.366856,0.908952,0.610462,0.231218,0.131646,0.310409
2,0.364167,0.114704,Farhan khan,0.010558,0.959399,0.298374,0.470475,0.70381,0.141244,0.209236,...,0.005799,0.467362,0.572785,0.377654,0.688039,0.440789,0.14822,0.819739,0.747088,0.102685
3,0.960544,0.586682,0.963718,0.880758,0.978795,0.107115,0.827065,0.467815,0.328094,0.316383,...,0.134026,0.846445,0.071297,0.859333,0.230959,0.502836,0.105629,0.364327,0.70219,0.645129
4,0.043891,0.18456,0.847224,0.748441,0.742416,0.088372,0.684224,0.427903,0.659834,0.399641,...,0.62044,0.466743,0.258783,0.436879,0.296283,0.703161,0.008582,0.105919,0.568904,0.678335
5,0.628084,0.402558,0.260758,0.759492,0.58056,0.995815,0.065872,0.83276,0.776327,0.199639,...,0.816484,0.947507,0.927775,0.351016,0.638024,0.801423,0.241477,0.960259,0.673789,0.249791
6,0.9851,0.910222,0.652911,0.932602,0.71803,0.993519,0.678462,0.614716,0.454768,0.915986,...,0.944275,0.253391,0.394918,0.932759,0.332104,0.830903,0.352974,0.324928,0.39589,0.114839
7,0.279562,0.328826,0.220852,0.807222,0.014365,0.818378,0.276491,0.349672,0.777606,0.673208,...,0.910504,0.38282,0.453797,0.142113,0.064745,0.978875,0.430081,0.753413,0.473277,0.231001
8,0.669178,0.520539,0.547996,0.116099,0.502321,0.768289,0.009131,0.815384,0.681192,0.39854,...,0.866363,0.973655,0.530364,0.383844,0.553049,0.991494,0.748771,0.426198,0.171036,0.615867
9,0.745397,0.484018,0.09654,0.86014,0.212576,0.360557,0.284776,0.66919,0.820684,0.069513,...,0.630969,0.145742,0.682557,0.82626,0.666156,0.676988,0.942898,0.635822,0.147524,0.380887

In [ ]:
newdf.sort_index(axis = 0, ascending = False)

,0,1,2,3,4,5,6,7,8,9
9999,0.034417,0.310409,0.102685,0.645129,0.678335,0.249791,0.114839,0.231001,0.615867,0.380887
9998,0.535498,0.131646,0.747088,0.702190,0.568904,0.673789,0.395890,0.473277,0.171036,0.147524
9997,0.928524,0.231218,0.819739,0.364327,0.105919,0.960259,0.324928,0.753413,0.426198,0.635822
9996,0.560311,0.610462,0.14822,0.105629,0.008582,0.241477,0.352974,0.430081,0.748771,0.942898
9995,0.709617,0.908952,0.440789,0.502836,0.703161,0.801423,0.830903,0.978875,0.991494,0.676988
...,...,...,...,...,...,...,...,...,...,...
4,0.566893,0.852146,0.959399,0.978795,0.742416,0.580560,0.718030,0.014365,0.502321,0.212576
3,0.665162,0.598727,0.010558,0.880758,0.748441,0.759492,0.932602,0.807222,0.116099,0.860140
2,0.341927,0.653088,Farhan khan,0.963718,0.847224,0.260758,0.652911,0.220852,0.547996,0.096540
1,0.109137,0.392457,0.114704,0.586682,0.184560,0.402558,0.910222,0.328826,0.520539,0.484018
0,1000000000,0.494204,0.364167,0.960544,0.043891,0.628084,0.985100,0.279562,0.669178,0.745397

In [ ]:
newdf.sort_index(axis = 1, ascending = False)

,9,8,7,6,5,4,3,2,1,0
0,0.745397,0.669178,0.279562,0.985100,0.628084,0.043891,0.960544,0.364167,0.494204,1000000000
1,0.484018,0.520539,0.328826,0.910222,0.402558,0.184560,0.586682,0.114704,0.392457,0.109137
2,0.096540,0.547996,0.220852,0.652911,0.260758,0.847224,0.963718,Farhan khan,0.653088,0.341927
3,0.860140,0.116099,0.807222,0.932602,0.759492,0.748441,0.880758,0.010558,0.598727,0.665162
4,0.212576,0.502321,0.014365,0.718030,0.580560,0.742416,0.978795,0.959399,0.852146,0.566893
...,...,...,...,...,...,...,...,...,...,...
9995,0.676988,0.991494,0.978875,0.830903,0.801423,0.703161,0.502836,0.440789,0.908952,0.709617
9996,0.942898,0.748771,0.430081,0.352974,0.241477,0.008582,0.105629,0.14822,0.610462,0.560311
9997,0.635822,0.426198,0.753413,0.324928,0.960259,0.105919,0.364327,0.819739,0.231218,0.928524
9998,0.147524,0.171036,0.473277,0.395890,0.673789,0.568904,0.702190,0.747088,0.131646,0.535498
9999,0.380887,0.615867,0.231001,0.114839,0.249791,0.678335,0.645129,0.102685,0.310409,0.034417

In [ ]:
newdf.head()

,0,1,2,3,4,5,6,7,8,9
0,1000000000,0.494204,0.364167,0.960544,0.043891,0.628084,0.985100,0.279562,0.669178,0.745397
1,0.109137,0.392457,0.114704,0.586682,0.184560,0.402558,0.910222,0.328826,0.520539,0.484018
2,0.341927,0.653088,Farhan khan,0.963718,0.847224,0.260758,0.652911,0.220852,0.547996,0.096540
3,0.665162,0.598727,0.010558,0.880758,0.748441,0.759492,0.932602,0.807222,0.116099,0.860140
4,0.566893,0.852146,0.959399,0.978795,0.742416,0.580560,0.718030,0.014365,0.502321,0.212576

In [ ]:
type(newdf[1])

pandas.core.series.Series

In [ ]:
newdf2 = newdf.copy()

In [ ]:
newdf

,0,1,2,3,4,5,6,7,8,9
0,1000000000,0.494204,0.364167,0.960544,0.043891,0.628084,0.985100,0.279562,0.669178,0.745397
1,0.109137,0.392457,0.114704,0.586682,0.184560,0.402558,0.910222,0.328826,0.520539,0.484018
2,0.341927,0.653088,Farhan khan,0.963718,0.847224,0.260758,0.652911,0.220852,0.547996,0.096540
3,0.665162,0.598727,0.010558,0.880758,0.748441,0.759492,0.932602,0.807222,0.116099,0.860140
4,0.566893,0.852146,0.959399,0.978795,0.742416,0.580560,0.718030,0.014365,0.502321,0.212576
...,...,...,...,...,...,...,...,...,...,...
9995,0.709617,0.908952,0.440789,0.502836,0.703161,0.801423,0.830903,0.978875,0.991494,0.676988
9996,0.560311,0.610462,0.14822,0.105629,0.008582,0.241477,0.352974,0.430081,0.748771,0.942898
9997,0.928524,0.231218,0.819739,0.364327,0.105919,0.960259,0.324928,0.753413,0.426198,0.635822
9998,0.535498,0.131646,0.747088,0.702190,0.568904,0.673789,0.395890,0.473277,0.171036,0.147524
9999,0.034417,0.310409,0.102685,0.645129,0.678335,0.249791,0.114839,0.231001,0.615867,0.380887

In [ ]:
newdf.loc[0][0] = 9999

/tmp/ipython-input-159696048.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf.loc[0][0] = 9999

In [ ]:
newdf.head(4)

,0,1,2,3,4,5,6,7,8,9
0,1000000000,0.494204,0.364167,0.960544,0.043891,0.628084,0.985100,0.279562,0.669178,0.745397
1,0.109137,0.392457,0.114704,0.586682,0.184560,0.402558,0.910222,0.328826,0.520539,0.484018
2,0.341927,0.653088,Farhan khan,0.963718,0.847224,0.260758,0.652911,0.220852,0.547996,0.096540
3,0.665162,0.598727,0.010558,0.880758,0.748441,0.759492,0.932602,0.807222,0.116099,0.860140

In [ ]:
newdf.columns = list("GUFRANKHAN")

In [ ]:
newdf

,G,U,F,R,A,N,K,H,A,N
0,1000000000,0.494204,0.364167,0.960544,0.043891,0.628084,0.985100,0.279562,0.669178,0.745397
1,0.109137,0.392457,0.114704,0.586682,0.184560,0.402558,0.910222,0.328826,0.520539,0.484018
2,0.341927,0.653088,Farhan khan,0.963718,0.847224,0.260758,0.652911,0.220852,0.547996,0.096540
3,0.665162,0.598727,0.010558,0.880758,0.748441,0.759492,0.932602,0.807222,0.116099,0.860140
4,0.566893,0.852146,0.959399,0.978795,0.742416,0.580560,0.718030,0.014365,0.502321,0.212576
...,...,...,...,...,...,...,...,...,...,...
9995,0.709617,0.908952,0.440789,0.502836,0.703161,0.801423,0.830903,0.978875,0.991494,0.676988
9996,0.560311,0.610462,0.14822,0.105629,0.008582,0.241477,0.352974,0.430081,0.748771,0.942898
9997,0.928524,0.231218,0.819739,0.364327,0.105919,0.960259,0.324928,0.753413,0.426198,0.635822
9998,0.535498,0.131646,0.747088,0.702190,0.568904,0.673789,0.395890,0.473277,0.171036,0.147524
9999,0.034417,0.310409,0.102685,0.645129,0.678335,0.249791,0.114839,0.231001,0.615867,0.380887

In [ ]:
newdf.loc[0,'A'] = 20000000

In [ ]:
newdf.head()

,G,U,F,R,A,N,K,H,A,N
0,1000000000,0.494204,0.364167,0.960544,2.000000e+07,0.628084,0.985100,0.279562,2.000000e+07,0.745397
1,0.109137,0.392457,0.114704,0.586682,1.845598e-01,0.402558,0.910222,0.328826,5.205394e-01,0.484018
2,0.341927,0.653088,Farhan khan,0.963718,8.472236e-01,0.260758,0.652911,0.220852,5.479960e-01,0.096540
3,0.665162,0.598727,0.010558,0.880758,7.484410e-01,0.759492,0.932602,0.807222,1.160994e-01,0.860140
4,0.566893,0.852146,0.959399,0.978795,7.424163e-01,0.580560,0.718030,0.014365,5.023208e-01,0.212576

In [ ]:
newdf.drop('G', axis = 1)

,U,F,R,A,N,K,H,A,N
0,0.494204,0.364167,0.960544,2.000000e+07,0.628084,0.985100,0.279562,2.000000e+07,0.745397
1,0.392457,0.114704,0.586682,1.845598e-01,0.402558,0.910222,0.328826,5.205394e-01,0.484018
2,0.653088,Farhan khan,0.963718,8.472236e-01,0.260758,0.652911,0.220852,5.479960e-01,0.096540
3,0.598727,0.010558,0.880758,7.484410e-01,0.759492,0.932602,0.807222,1.160994e-01,0.860140
4,0.852146,0.959399,0.978795,7.424163e-01,0.580560,0.718030,0.014365,5.023208e-01,0.212576
...,...,...,...,...,...,...,...,...,...
9995,0.908952,0.440789,0.502836,7.031614e-01,0.801423,0.830903,0.978875,9.914936e-01,0.676988
9996,0.610462,0.14822,0.105629,8.581503e-03,0.241477,0.352974,0.430081,7.487714e-01,0.942898
9997,0.231218,0.819739,0.364327,1.059190e-01,0.960259,0.324928,0.753413,4.261976e-01,0.635822
9998,0.131646,0.747088,0.702190,5.689038e-01,0.673789,0.395890,0.473277,1.710364e-01,0.147524
9999,0.310409,0.102685,0.645129,6.783351e-01,0.249791,0.114839,0.231001,6.158667e-01,0.380887

In [ ]:
newdf.drop('N', axis = 1)

,G,U,F,R,A,K,H,A
0,1000000000,0.494204,0.364167,0.960544,2.000000e+07,0.985100,0.279562,2.000000e+07
1,0.109137,0.392457,0.114704,0.586682,1.845598e-01,0.910222,0.328826,5.205394e-01
2,0.341927,0.653088,Farhan khan,0.963718,8.472236e-01,0.652911,0.220852,5.479960e-01
3,0.665162,0.598727,0.010558,0.880758,7.484410e-01,0.932602,0.807222,1.160994e-01
4,0.566893,0.852146,0.959399,0.978795,7.424163e-01,0.718030,0.014365,5.023208e-01
...,...,...,...,...,...,...,...,...
9995,0.709617,0.908952,0.440789,0.502836,7.031614e-01,0.830903,0.978875,9.914936e-01
9996,0.560311,0.610462,0.14822,0.105629,8.581503e-03,0.352974,0.430081,7.487714e-01
9997,0.928524,0.231218,0.819739,0.364327,1.059190e-01,0.324928,0.753413,4.261976e-01
9998,0.535498,0.131646,0.747088,0.702190,5.689038e-01,0.395890,0.473277,1.710364e-01
9999,0.034417,0.310409,0.102685,0.645129,6.783351e-01,0.114839,0.231001,6.158667e-01

In [ ]:
 newdf=newdf.drop('N', axis = 1)

In [ ]:
newdf.head()

,G,U,F,R,A,K,H,A
0,1000000000,0.494204,0.364167,0.960544,2.000000e+07,0.985100,0.279562,2.000000e+07
1,0.109137,0.392457,0.114704,0.586682,1.845598e-01,0.910222,0.328826,5.205394e-01
2,0.341927,0.653088,Farhan khan,0.963718,8.472236e-01,0.652911,0.220852,5.479960e-01
3,0.665162,0.598727,0.010558,0.880758,7.484410e-01,0.932602,0.807222,1.160994e-01
4,0.566893,0.852146,0.959399,0.978795,7.424163e-01,0.718030,0.014365,5.023208e-01

In [ ]:
newdf.loc[[1,2],['G','U']]

          G         U
1  0.109137  0.392457
2  0.341927  0.653088

In [ ]:
newdf.head()

,G,U,F,R,A,K,H,A
0,1000000000,0.494204,0.364167,0.960544,2.000000e+07,0.985100,0.279562,2.000000e+07
1,0.109137,0.392457,0.114704,0.586682,1.845598e-01,0.910222,0.328826,5.205394e-01
2,0.341927,0.653088,Farhan khan,0.963718,8.472236e-01,0.652911,0.220852,5.479960e-01
3,0.665162,0.598727,0.010558,0.880758,7.484410e-01,0.932602,0.807222,1.160994e-01
4,0.566893,0.852146,0.959399,0.978795,7.424163e-01,0.718030,0.014365,5.023208e-01

In [ ]:
newdf.loc[[1,2],:]

,G,U,F,R,A,K,H,A
1,0.109137,0.392457,0.114704,0.586682,0.184560,0.910222,0.328826,0.520539
2,0.341927,0.653088,Farhan khan,0.963718,0.847224,0.652911,0.220852,0.547996

In [ ]:
newdf.head()

,G,U,F,R,A,K,H,A
0,1000000000,0.494204,0.364167,0.960544,2.000000e+07,0.985100,0.279562,2.000000e+07
1,0.109137,0.392457,0.114704,0.586682,1.845598e-01,0.910222,0.328826,5.205394e-01
2,0.341927,0.653088,Farhan khan,0.963718,8.472236e-01,0.652911,0.220852,5.479960e-01
3,0.665162,0.598727,0.010558,0.880758,7.484410e-01,0.932602,0.807222,1.160994e-01
4,0.566893,0.852146,0.959399,0.978795,7.424163e-01,0.718030,0.014365,5.023208e-01

In [ ]:
newdf.head(10)

,G,U,F,R,A,K,H,A
0,1000000000,0.494204,0.364167,0.960544,2.000000e+07,0.985100,0.279562,2.000000e+07
1,0.109137,0.392457,0.114704,0.586682,1.845598e-01,0.910222,0.328826,5.205394e-01
2,0.341927,0.653088,Farhan khan,0.963718,8.472236e-01,0.652911,0.220852,5.479960e-01
3,0.665162,0.598727,0.010558,0.880758,7.484410e-01,0.932602,0.807222,1.160994e-01
4,0.566893,0.852146,0.959399,0.978795,7.424163e-01,0.718030,0.014365,5.023208e-01
5,0.014012,0.429913,0.298374,0.107115,8.837221e-02,0.993519,0.818378,7.682892e-01
6,0.820483,0.944443,0.470475,0.827065,6.842242e-01,0.678462,0.276491,9.131408e-03
7,0.865744,0.145462,0.70381,0.467815,4.279032e-01,0.614716,0.349672,8.153843e-01
8,0.466946,0.524548,0.141244,0.328094,6.598337e-01,0.454768,0.777606,6.811921e-01
9,0.389425,0.384371,0.209236,0.316383,3.996407e-01,0.915986,0.673208,3.985398e-01

In [ ]:
newdf.iloc[0,5]

np.float64(0.9851004085794463)

In [ ]:
newdf.iloc[[4,5],[5,7]]

          K         A
4  0.718030  0.502321
5  0.993519  0.768289

In [ ]:
newdf.head(3)

,G,U,F,R,A,K,H,A
0,1000000000,0.494204,0.364167,0.960544,2.000000e+07,0.985100,0.279562,2.000000e+07
1,0.109137,0.392457,0.114704,0.586682,1.845598e-01,0.910222,0.328826,5.205394e-01
2,0.341927,0.653088,Farhan khan,0.963718,8.472236e-01,0.652911,0.220852,5.479960e-01

In [ ]:
newdf.drop(2)

,G,U,F,R,A,K,H,A
0,1000000000,0.494204,0.364167,0.960544,2.000000e+07,0.985100,0.279562,2.000000e+07
1,0.109137,0.392457,0.114704,0.586682,1.845598e-01,0.910222,0.328826,5.205394e-01
3,0.665162,0.598727,0.010558,0.880758,7.484410e-01,0.932602,0.807222,1.160994e-01
4,0.566893,0.852146,0.959399,0.978795,7.424163e-01,0.718030,0.014365,5.023208e-01
5,0.014012,0.429913,0.298374,0.107115,8.837221e-02,0.993519,0.818378,7.682892e-01
...,...,...,...,...,...,...,...,...
9995,0.709617,0.908952,0.440789,0.502836,7.031614e-01,0.830903,0.978875,9.914936e-01
9996,0.560311,0.610462,0.14822,0.105629,8.581503e-03,0.352974,0.430081,7.487714e-01
9997,0.928524,0.231218,0.819739,0.364327,1.059190e-01,0.324928,0.753413,4.261976e-01
9998,0.535498,0.131646,0.747088,0.702190,5.689038e-01,0.395890,0.473277,1.710364e-01
9999,0.034417,0.310409,0.102685,0.645129,6.783351e-01,0.114839,0.231001,6.158667e-01

In [ ]:
newdf.drop([0,4], axis = 0, inplace = True)

In [ ]:
newdf.head(3)

,G,U,F,R,A,K,H,A
1,0.109137,0.392457,0.114704,0.586682,0.184560,0.910222,0.328826,0.520539
2,0.341927,0.653088,Farhan khan,0.963718,0.847224,0.652911,0.220852,0.547996
3,0.665162,0.598727,0.010558,0.880758,0.748441,0.932602,0.807222,0.116099

In [ ]:
newdf['U'].isnull()

1       False
2       False
3       False
5       False
6       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Name: U, Length: 9998, dtype: bool

In [ ]:
newdf['G','U'] = None

In [ ]:
newdf.head()

,G,U,F,R,A,K,H,A,"(G, U)"
1,0.109137,0.392457,0.114704,0.586682,0.184560,0.910222,0.328826,0.520539,None
2,0.341927,0.653088,Farhan khan,0.963718,0.847224,0.652911,0.220852,0.547996,None
3,0.665162,0.598727,0.010558,0.880758,0.748441,0.932602,0.807222,0.116099,None
5,0.014012,0.429913,0.298374,0.107115,0.088372,0.993519,0.818378,0.768289,None
6,0.820483,0.944443,0.470475,0.827065,0.684224,0.678462,0.276491,0.009131,None

In [ ]:
newdf.head()

,G,U,F,R,A,K,H,A,"(G, U)"
1,0.109137,0.392457,0.114704,0.586682,0.184560,0.910222,0.328826,0.520539,None
2,0.341927,0.653088,Farhan khan,0.963718,0.847224,0.652911,0.220852,0.547996,None
3,0.665162,0.598727,0.010558,0.880758,0.748441,0.932602,0.807222,0.116099,None
5,0.014012,0.429913,0.298374,0.107115,0.088372,0.993519,0.818378,0.768289,None
6,0.820483,0.944443,0.470475,0.827065,0.684224,0.678462,0.276491,0.009131,None

In [ ]:
newdf.loc[:,['G']] = 34

In [ ]:
newdf.head()

,G,U,F,R,A,K,H,A,"(G, U)"
1,34,0.392457,0.114704,0.586682,0.184560,0.910222,0.328826,0.520539,None
2,34,0.653088,Farhan khan,0.963718,0.847224,0.652911,0.220852,0.547996,None
3,34,0.598727,0.010558,0.880758,0.748441,0.932602,0.807222,0.116099,None
5,34,0.429913,0.298374,0.107115,0.088372,0.993519,0.818378,0.768289,None
6,34,0.944443,0.470475,0.827065,0.684224,0.678462,0.276491,0.009131,None

In [ ]:
 df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                     "toy": [np.nan, 'Batmobile', 'Bullwhip'],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"),
                             pd.NaT]})

In [ ]:
df.head()

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [ ]:
df.dropna()

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [ ]:
df.dropna(how = 'all', axis =1)

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [ ]:
df.drop_duplicates(subset = ['name'], keep = False)

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [ ]:
df.head()

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [ ]:
df.shape

(3, 3)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   toy     2 non-null      object
 2   born    1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(2)
memory usage: 204.0+ bytes

In [ ]:
df['born'].value_counts(dropna=False)

born
NaT           2
1940-04-25    1
Name: count, dtype: int64

In [ ]:
df['born'].value_counts(dropna=True)

born
1940-04-25    1
Name: count, dtype: int64

In [ ]:
df.notnull()

   name    toy   born
0  True  False  False
1  True   True   True
2  True   True  False

In [ ]:
df.isnull()

    name    toy   born
0  False   True   True
1  False  False  False
2  False  False   True

In [ ]:
data ={
    'A':[100,2000,300],
    'B':[1000,5000,10000]
}

In [ ]:
data

{'A': [100, 2000, 300], 'B': [1000, 5000, 10000]}

In [ ]:
import pandas as pd

data_df = pd.DataFrame(data)
data_df.describe()

                 A             B
count     3.000000      3.000000
mean    800.000000   5333.333333
std    1044.030651   4509.249753
min     100.000000   1000.000000
25%     200.000000   3000.000000
50%     300.000000   5000.000000
75%    1150.000000   7500.000000
max    2000.000000  10000.000000

In [ ]:
data_df['A'] = pd.to_numeric(data_df['A'])
data_df.mean()

A     800.000000
B    5333.333333
dtype: float64

In [ ]:
data_df.corr()

          A         B
A  1.000000  0.031862
B  0.031862  1.000000

In [ ]:
data_df.max()

A     2000
B    10000
dtype: int64

In [ ]:
data_df.min()

A     100
B    1000
dtype: int64

In [ ]:
data_df.median()

A     300.0
B    5000.0
dtype: float64

In [ ]:
data_df.std()

A    1044.030651
B    4509.249753
dtype: float64